name: statusnap
version: '1'
summary: proba snap
description: |
    status of snap
grade: stable
confinement: devmode
apps:
  statusnap:
    command: bin/statusnap
    plugin: python

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools 

