name: statusnap
version: '1'
summary: proba snap
description: |
    status of snap
grade: stable
confinement: devmode
parts:
  statusnap:
    command: bin/statusnap
    source: https://github.com/kocicjelena/statusnap.git
    source-tag: v1.1.3
    plugin: python
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools
