name: statusnap
version: '1'
summary: proba snap
description: |
    status of snap
grade: stable
confinement: devmode
apps:
  statusnap:
    command: status
    plugin: python

parts:
  statusnap:
      source: https://github.com/kocicjelena/statusnap.git
      source-tag: v1.1.3
      plugin: python
  

