name: statusnap
version: '1.1.3'
summary: proba snap
description: |
    status of snap
grade: stable
confinement: devmode
parts:
  httpstat:
    source: https://github.com/kocicjelena/statusnap.git
    source-tag: v1.1.3
    plugin: python
