name: statusnap
version: '1'
summary: proba snap
description: |
    status of snap
grade: stable
confinement: devmode
apps:
  statusnap:
    command: bin/statusnap
    plugin: python

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools 
  gnu-bash:
      source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
      plugin: autotools
      configflags: ["--infodir=/var/bash/info"]
  statusnap:
      source: https://github.com/kocicjelena/statusnap.git
      source-tag: v1.1.3
      plugin: python
  

